version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: itdrive-postgres
    environment:
      POSTGRES_DB: tikhon-pc
      POSTGRES_USER: tikhon-pc
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tikhon-pc -d tikhon-pc"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: