spring:
  application:
    name: itdrive
  
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/tikhon-pc
      username: ${DB_USERNAME:tikhon-pc}
      password: ${DB_PASSWORD:123}
      driver-class-name: org.postgresql.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:itdrive-secret-key-for-jwt-token-generation-2025}
  expiration: 86400000 # 24 hours
